sources:
  -
    name: radarrelay
    market_list:
      url: https://api.radarrelay.com/v3/markets
      jq: map(.id|split("-"))

    url: https://api.radarrelay.com/v3/markets/%base%-%quote%/book
    jq:
      bids: >-
        .bids |
        map([(.remainingBaseTokenAmount | tonumber), (.price | tonumber), .createdDate])
      asks: >-
        .asks |
        map([(.remainingBaseTokenAmount | tonumber), (.price | tonumber), .createdDate])

  -
    name: ddex-v4
    market_list:
      url: https://api.ddex.io/v4/markets
      jq: .data.markets | map([.baseAsset, .quoteAsset])

    url: https://api.ddex.io/v4/markets/%base%-%quote%/orderbook?level=3
    jq:
      bids: >-
        .data.orderbook.bids |
        if length > 0 then map([(.amount | tonumber), (.price | tonumber)]) else [] end
      asks: >-
        .data.orderbook.asks |
        if length > 0 then map([(.amount | tonumber), (.price | tonumber)]) else [] end

  -
    name: ddex-v3
    market_list:
      url: https://api.ddex.io/v3/markets
      jq: .data.markets | map([.baseToken, .quoteToken])

    url: https://api.ddex.io/v3/markets/%base%-%quote%/orderbook
    jq:
      bids: >-
        .data.orderBook.bids |
        map([(.amount | tonumber), (.price | tonumber)])
      asks: >-
        .data.orderBook.asks |
        map([(.amount | tonumber), (.price | tonumber)])

