---
  -
    name: tokenstore
    active: false
    maker_fee: 0.0
    taker_fee: 0.0
    market_list:
      url: https://v1-1.api.token.store/pairs
      jq: |
        map({id: .id, 
        base: .fromSymbol, 
        quote: .toSymbol, 
        price_decimals: 8, 
        quantity_decimals: 8, 
        min_order_size: "1",
        base_contract: "xx00xx",
        quote_contract: "xx00xx"
        })

    url: https://v1-1.api.token.store/orderbook/%quote%_%base%
    jq:
      bids: >-
        .bids |
        map([(.remainingBaseTokenAmount | tonumber), (.price | tonumber), .createdDate])
      asks: >-
        .asks |
        map([(.remainingBaseTokenAmount | tonumber), (.price | tonumber), .createdDate])
    ws_url: wss://ws.radarrelay.com/v3
  -
    name: radarrelay
    active: true
    maker_fee: 0.0
    taker_fee: 0.0
    market_list:
      url: https://api.radarrelay.com/v3/markets
      jq: |
        map({id: .id, 
        base: (.id|split("-")[0]), 
        quote: (.id|split("-")[1]), 
        price_decimals: .baseTokenDecimals, 
        quantity_decimals: .quoteTokenDecimals, 
        min_order_size: .minOrderSize,
        base_contract: .baseTokenAddress,
        quote_contract: .quoteTokenAddress
        })

    url: https://api.radarrelay.com/v3/markets/%base%-%quote%/book
    jq:
      bids: >-
        .bids |
        map([(.volume | tonumber), (.price | tonumber)])
      asks: >-
        .asks |
        map([(.volume | tonumber), (.price | tonumber)])
    ws_url: wss://ws.radarrelay.com/v3
    #0x SRA ws_url: wss://ws.radarrelay.com/0x/v3
  -
    name: ddex-v3
    active: true
    maker_fee: 0.1
    taker_fee: 0.3
    market_list:
      url: https://api.ddex.io/v3/markets
      jq: |
        .data.markets | map({
          base: (.id|split("-")[0]), 
          quote: (.id|split("-")[1]), 
          price_decimals: .priceDecimals, 
          quantity_decimals: .amountDecimals, 
          min_order_size: .minOrderSize,
          base_contract: .baseTokenAddress,
          quote_contract: .quoteTokenAddress
        })

    url: https://api.ddex.io/v3/markets/%base%-%quote%/orderbook
    jq:
      bids: >-
        .data.orderBook.bids |
        map([(.amount | tonumber), (.price | tonumber)])
      asks: >-
        .data.orderBook.asks |
        map([(.amount | tonumber), (.price | tonumber)])
    ws_url: wss://ws.ddex.io/v3

  -
    name: ddex-v4
    active: true
    maker_fee: 0.1
    taker_fee: 0.3
    market_list:
      url: https://api.ddex.io/v4/markets
      jq: |
        .data.markets | map({
          base: .baseAsset, 
          quote: .quoteAsset, 
          price_decimals: .priceDecimals, 
          quantity_decimals: .amountDecimals, 
          min_order_size: .minOrderSize,
          base_contract: .baseAssetAddress,
          quote_contract: .quoteAssetAddress
        })

    url: https://api.ddex.io/v4/markets/%base%-%quote%/orderbook?level=3
    jq:
      bids: >-
        .data.orderbook.bids |
        if length > 0 then map([(.amount | tonumber), (.price | tonumber)]) else [] end
      asks: >-
        .data.orderbook.asks |
        if length > 0 then map([(.amount | tonumber), (.price | tonumber)]) else [] end
    ws_url: wss://ws.ddex.io/v4

